image: marioarduini/rumble-source:2020-11-23

stages:
  - build
  - spark-tests
  - other-tests

Build:
  stage: build
  artifacts:
    paths:
      - target/
  script:
    - ant -buildfile build_antlr_parser.xml generate-parser -Dantlr.jar=lib/antlr-4.9.3-complete.jar
    - mvn clean compile assembly:single


StaticTypingTest:
  stage: other-tests
  script:
    - mvn -Dtest=StaticTypeTests test -Dmaven.test.redirectTestOutputToFile=true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.StaticTypeTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.StaticTypeTests.xml
