image: maven:3.9.9-eclipse-temurin-11

stages:
  - build
  - spark-tests
  - other-tests

Build:
  stage: build
  artifacts:
    paths:
      - target/
  script:
    - mvn clean compile assembly:single

trigger_job:
  stage: spark-tests
  trigger:
    project: gfourny/rumble-test-suite

SparkRuntimeTest:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTests test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.SparkRuntimeTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.SparkRuntimeTests.xml

SparkRuntimeTestsNativeDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsNativeDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.SparkRuntimeTestsNativeDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.SparkRuntimeTestsNativeDeactivated.xml

SparkRuntimeTestsDataFramesDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsDataFramesDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.SparkRuntimeTestsDataFramesDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.SparkRuntimeTestsDataFramesDeactivated.xml

SparkRuntimeTestsParallelismDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsParallelismDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.SparkRuntimeTestsParallelismDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.SparkRuntimeTestsParallelismDeactivated.xml

JavaAPITest:
  stage: other-tests
  script:
    - mvn -Dtest=JavaAPITest test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.JavaAPITest.xml
    reports:
      junit: target/surefire-reports/TEST-iq.JavaAPITest.xml

FrontendTests:
  stage: other-tests
  script:
    - mvn -Dtest=FrontendTests test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.FrontendTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.FrontendTests.xml

RuntimeTests:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTests test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.RuntimeTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.RuntimeTests.xml

RuntimeTestsNoParallelism:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTestsNoParallelism test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.RuntimeTestsNoParallelism.xml
    reports:
      junit: target/surefire-reports/TEST-iq.RuntimeTestsNoParallelism.xml

RuntimeTestsNoInlining:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTestsNoInlining test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.RuntimeTestsNoInlining.xml
    reports:
      junit: target/surefire-reports/TEST-iq.RuntimeTestsNoInlining.xml

NativeFLWORRuntimeTests:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTests test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.NativeFLWORRuntimeTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.NativeFLWORRuntimeTests.xml

NativeFLWORRuntimeTestsNativeDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsNativeDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsNativeDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsNativeDeactivated.xml

NativeFLWORRuntimeTestsDataFramesDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsDataFramesDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsDataFramesDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsDataFramesDeactivated.xml

NativeFLWORRuntimeTestsParallelismDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsParallelismDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsParallelismDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.NativeFLWORRuntimeTestsParallelismDeactivated.xml

StaticTypingTest:
  stage: other-tests
  script:
    - mvn -Dtest=StaticTypeTests test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.StaticTypeTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.StaticTypeTests.xml

SpotlessTest:
  stage: other-tests
  script:
    - mvn spotless:check

MLTests:
  stage: other-tests
  script:
    - mvn -Dtest=MLTests test --log-file target/ml_test.log
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.MLTests.xml
    reports:
      junit: target/surefire-reports/TEST-iq.MLTests.xml

MLTestsNativeDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=MLTestsNativeDeactivated test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-iq.MLTestsNativeDeactivated.xml
    reports:
      junit: target/surefire-reports/TEST-iq.MLTestsNativeDeactivated.xml


