image: marioarduini/rumble-source:2020-11-23

stages:
  - build
  - spark-tests
  - other-tests

Build:
  stage: build
  artifacts:
    paths:
      - target/
  script:
    - ant -buildfile build_antlr_parser.xml generate-parser -Dantlr.jar=lib/antlr-4.9.3-complete.jar
    - mvn clean compile assembly:single

SparkRuntimeTest:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTests test

SparkRuntimeTestsNativeDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsNativeDeactivated test

SparkRuntimeTestsDataFramesDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsDataFramesDeactivated test

SparkRuntimeTestsParallelismDeactivated:
  stage: spark-tests
  script:
    - mvn -Dtest=SparkRuntimeTestsParallelismDeactivated test

JavaAPITest:
  stage: other-tests
  script:
    - mvn -Dtest=JavaAPITest test

FrontendTests:
  stage: other-tests
  script:
    - mvn -Dtest=FrontendTests test

RuntimeTests:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTests test

RuntimeTestsNoParallelism:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTestsNoParallelism test

RuntimeTestsNoInlining:
  stage: other-tests
  script:
    - mvn -Dtest=RuntimeTestsNoInlining test

NativeFLWORRuntimeTests:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTests test

NativeFLWORRuntimeTestsNativeDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsNativeDeactivated test

NativeFLWORRuntimeTestsDataFramesDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsDataFramesDeactivated test

NativeFLWORRuntimeTestsParallelismDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=NativeFLWORRuntimeTestsParallelismDeactivated test

StaticTypingTest:
  stage: other-tests
  script:
    - mvn -Dtest=StaticTypeTests test

SpotlessTest:
  stage: other-tests
  script:
    - mvn spotless:check

MLTests:
  stage: other-tests
  artifacts:
    name: "ML Tests log"
    paths:
      - target/ml_test.log
    when:
      always
    expire_in: 2 days
  script:
    - mvn -Dtest=MLTests test --log-file target/ml_test.log

MLTestsNativeDeactivated:
  stage: other-tests
  script:
    - mvn -Dtest=MLTestsNativeDeactivated test