site_name: Rumble 1.6.0 "Yucca" beta
pages:
  - '1. Documentation home': 'index.md'
  - '2. Getting started': 'Getting started.md'
  - '3. Run on a cluster': 'Run on a cluster.md'
  - '4. Run in Jupyter notebooks (experimental)': 'HTTPServer.md'
  - '5. The JSONiq language': 'JSONiq.md'
  - '6. Reading data': 'Input.md'
  - '7. Function library': 'Function library.md'
  - '8. CLI and HTTP parameters': 'CLI.md'
  - '9. Error codes': 'Error codes.md'
  - '10. Compile from GitHub': 'install.md'
  - '11. Licenses': 'Licenses.md'
theme: readthedocs
