# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install with Maven
      run: mvn install -DskipTests -Dgpg.skip --quiet
    - name: Compile with Maven
      run: mvn clean compile assembly:single
    - name: FrontendTests
      run: mvn -Dtest=FrontendTests test
    - name: RuntimeTests
      run: mvn -Dtest=RuntimeTests test
    - name: SparkRuntimeTests
      run: mvn -Dtest=SparkRuntimeTests test
    - name: JavaAPITest
      run: mvn -Dtest=JavaAPITest test
    - name: Spotless check
      run: mvn spotless:check
